### ISSUE TITLE
Pip install error

### ISSUE THREAD

**Issue by stevenle** [grow/jetway-client#1]
```
Collecting jetway from git+git://github.com/grow/jetway-client@master#egg=jetway (from -r requirements.txt (line 19))
  Cloning git://github.com/grow/jetway-client (to master) to /private/tmp/pip-build-T1y8EE/jetway
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/tmp/pip-build-T1y8EE/jetway/setup.py", line 19, in <module>
        install_requires=[str(ir.req) for ir in _install_requirements],
      File "/Library/Python/2.7/site-packages/pip-6.0.7-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements
        "parse_requirements() missing 1 required keyword argument: "
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/private/tmp/pip-build-T1y8EE/jetway/setup.py", line 19, in <module>
    
        install_requires=[str(ir.req) for ir in _install_requirements],
    
      File "/Library/Python/2.7/site-packages/pip-6.0.7-py2.7.egg/pip/req/req_file.py", line 19, in parse_requirements
    
        "parse_requirements() missing 1 required keyword argument: "
    
    TypeError: parse_requirements() missing 1 required keyword argument: 'session'
```

**Comment by stevenle** [comment]
I think this only happens in the latest version of pip (version 6.0+). Should be a quick fix, but I don't have dev access to this repo. Here's an example:

https://github.com/tweepy/tweepy/commit/9b4cb9eb123be05a925c1c6deaf0141699853644

**Comment by stevenle** [comment]
Just kidding, I do have access. Submitting pull request now.
